retrieveUnpackaged/objects/Appsubscriber__c.object
<CustomObject>
    <description>This Object Keeps Track of Access Permissions</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>Captures Users Address</description>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Capture Users City</description>
        <inlineHelpText>Please Enter Your City</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>This Field is used to store the access code</description>
        <inlineHelpText>Please Enter The Security Code Provided</inlineHelpText>
        <label>Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Captures Country of user</description>
        <inlineHelpText>Please Enter Your Country</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Captures User Email</description>
        <inlineHelpText>Please Enter Your Email</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PersonName__c</fullName>
        <description>Captures User Name</description>
        <inlineHelpText>Please Enter Yor Name</inlineHelpText>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Captures User Phone Number</description>
        <inlineHelpText>Please Enter Your Phone Number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Captures User State</description>
        <inlineHelpText>Please Enter Your State</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Request Sent&quot;</defaultValue>
        <description>Notifies The Security Code Request Status</description>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Users Zip Code</description>
        <inlineHelpText>Please Enter Your Zip Code</inlineHelpText>
        <label>Zip Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Appsubscriber</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appsubscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/AppRegistrationController.cls
public with sharing class AppRegistrationController {

    public List<Appsubscriber__c> SubscribeDetails {get;set;}
    public Boolean Formswitcher{get;set;}
    public Appsubscriber__c SubscribeObject{get; set;}
    public AppRegistrationController(ApexPages.StandardController controller) {
      InialFunctions();
    }
    public void InialFunctions()
    {
      SubscribeDetails=[SELECT Id,Email__c,Name,Code__c,Status__c from Appsubscriber__c limit 1 ];
      if (!SubscribeDetails.isEmpty())
      Formswitcher=true;
       else
      Formswitcher=false;
      SubscribeObject=new Appsubscriber__c();
    }
     public PageReference Save()
    {
        try {
            upsert SubscribeObject;
            sendEmailFunction(SubscribeObject);
            return SuceesRedirect();
        } catch (DmlException e) {
    
        }
       return null;
    }
     public PageReference Cancel()
    {
       
       return null;
    }
     public PageReference SubscribeUpdate()
    {
        try {
            SubscribeDetails[0].Status__c='Access Code Set';
            upsert SubscribeDetails;
            return SuceesRedirect();
        } catch (DmlException e) {
    
        }
       return null;
    }
    
    public PageReference SuceesRedirect()
    {
    PageReference pg = new PageReference('/apex/AppRegistration');
    pg.setRedirect(true);
    return pg;
    }
    
    Public void sendEmailFunction(Appsubscriber__c rec){
     Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
     String[] toAddresses = new String[] {'sushankotianriverdale@gmail.com'}; 
     mail.setToAddresses(toAddresses);
     mail.setSenderDisplayName(rec.Name);
     mail.setSubject('Access Code Request');
     mail.setBccSender(false);
     mail.setUseSignature(false);
     mail.setPlainTextBody('This is test email body. This mail is being sent from apex code');
     mail.setHtmlBody('Name:'+rec.PersonName__c+'<br/>Company Name:'+rec.Name+'<br/>Email: '+rec.Email__c+'<br/>Phone: '+rec.Phone__c+'<br/>Street: '+rec.Address__c+'<br/>City: '+rec.City__c+'<br/>State: '+rec.State__c+'<br/>Country: '+rec.Country__c+'<br/>Zip Code: '+rec.Zip_Code__c);
     Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
 } 

}