retrieveUnpackaged/objects/Appsubscriber__c.object
<CustomObject>
    <description>This Object Keeps Track of Access Permissions</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>This Field is used to store the access code</description>
        <inlineHelpText>Please Enter The Security Code Provided</inlineHelpText>
        <label>Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Captures User Email</description>
        <inlineHelpText>Please Enter Your Email</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PersonName__c</fullName>
        <description>Captures User Name</description>
        <inlineHelpText>Please Enter Yor Name</inlineHelpText>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Appsubscriber</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appsubscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/AppAcessControllerTest.cls
@isTest
public class AppAcessControllerTest {
    static testmethod void myunittest(){
        
        Lead l=new Lead();
        AppAcessController aas=new AppAcessController(new ApexPages.StandardController(l));
       
        Appsubscriber__c a=new Appsubscriber__c();
         a.name='test';
         a.Email__c='test@test.com';
         a.PersonName__c='test';
         a.Code__c='test';
         insert a;
         Appsubscriber__c asl=[select id,name,Code__c,PersonName__c,Email__c from Appsubscriber__c where id=:a.id];
        System.assertEquals(asl.name,'test');
        System.assertEquals(asl.personname__c,a.personname__c);
        System.assertEquals(asl.Code__c,a.Code__c);
        System.assertEquals(asl.email__c,a.email__c);
        PageReference pageRef = Page.InsightBASE_Dashboard;
        pageRef.getParameters().put('SecurityCode',a.Code__c );
        Test.setCurrentPage(pageRef);
        
    }
    
    
}