retrieveUnpackaged/objects/Appsubscriber__c.object
<CustomObject>
    <description>This Object Keeps Track of Access Permissions</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>This Field is used to store the access code</description>
        <inlineHelpText>Please Enter The Security Code Provided</inlineHelpText>
        <label>Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Captures User Email</description>
        <inlineHelpText>Please Enter Your Email</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Request Sent&quot;</defaultValue>
        <description>Notifies The Security Code Request Status</description>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Appsubscriber</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appsubscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/AppAcessController.cls
public with sharing class AppAcessController {

public String SecurityCode{get;set;}
public String leademail{get;set;}


    public AppAcessController(ApexPages.StandardController controller) {
     List<Lead> Leadobject=[SELECT Email from Lead where Id=:controller.getId() limit 1 ];
     if (!Leadobject.isEmpty())
     {
       Blob beforeblob= Blob.valueOf(Leadobject[0].Email);
       leademail=EncodingUtil.base64Encode(beforeblob);
     }  

    List<Appsubscriber__c> Appsubscriberobject=[SELECT Id,Email__c,Name,Code__c,Status__c from Appsubscriber__c limit 1 ];
     if (!Appsubscriberobject.isEmpty())
       SecurityCode=Appsubscriberobject[0].Code__c;
   }



}