retrieveUnpackaged/objects/Appsubscriber__c.object
<CustomObject>
    <description>This Object Keeps Track of Access Permissions</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Captures User Email</description>
        <inlineHelpText>Please Enter Your Email</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PersonName__c</fullName>
        <description>Captures User Name</description>
        <inlineHelpText>Please Enter Yor Name</inlineHelpText>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Appsubscriber</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appsubscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/AppRegistrationControllerTest.cls
@isTest
public class AppRegistrationControllerTest {
    static testmethod void myunittest(){
         Lead l=new Lead();
        AppRegistrationController arc=new AppRegistrationController(new ApexPages.StandardController(l));
        
        arc.InialFunctions();
        Appsubscriber__c a=new Appsubscriber__c();
        a.name='test';
        a.PersonName__c='test';
        a.Email__c='test@test.com';
        insert a;
        Appsubscriber__c asl=[select id,name,PersonName__c,Email__c from Appsubscriber__c where id=:a.id];
        System.assertEquals(asl.name,'test');
        System.assertEquals(asl.personname__c,a.personname__c);
        System.assertEquals(asl.email__c,a.email__c);
        arc.InialFunctions();
        arc.Save();
        arc.Cancel();
        arc.SubscribeUpdate();
        arc.SuceesRedirect();
        arc.sendEmailFunction(a);
    }
}