retrieveUnpackaged/objects/Contact_Email_Changes__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Email Changes</relationshipLabel>
        <relationshipName>Contact_Email_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Contact Email Changes</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contact Email Changes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Email Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/ContactNotify.cls
public class ContactNotify {

    public PageReference UpdateContact() {
    
     //update con;
     Contact_Email_Changes__c ce=new Contact_Email_Changes__c();
     ce.email__c=con.email;
     ce.Contact__c=con.id;
     insert ce;
     
        return null;
    }


public contact con{get;set;}
public ContactNotify(){

String Cid=ApexPages.currentPage().getParameters().get('CId');
con=new Contact();
if(Cid!=null){
con=[select id,name,email,lastname from Contact where id=:Cid];
}

} 

}