retrieveUnpackaged/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/apsoql2.cls
public class apsoql2 {

    public String stat { get; set; }

    public PageReference m3() {
    list<course__c> c1=new list<course__c>(); 
    
    c1=[select name from course__c where fee__c=9000];
    
    delete c1;
        return null;
    }


    public PageReference m2() {
     
           course__c  cu=[select name from course__c where fee__c=9000];
      cu.name='.net'; 
      cu.duration__c='2 months';
      update cu;
      stat='Records updated';
        return null;
    }


    public PageReference m1() {
      course__c cc=new course__c();
      cc.name='Java';
      cc.fee__c=2000;
      insert cc;
      stat='Records Inserted';
    
        return null;
    }

}