retrieveUnpackaged/objects/login__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>login</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/aloginvar.cls
public class aloginvar {

    public PageReference m1() {
    integer n= [select count() from login__c where name=:uid and Password__c=:pwd];
        if(n>=1)
          stat ='Login Success';
          else 
          stat =' Login Failed';
        
        
        return null;
    }

    public String stat {get;set;}
    
    public String pwd { get; set; }

    public String uid { get; set; }
}