retrieveUnpackaged/objects/timesheet__c.object
<CustomObject>
    <fields>
        <fullName>First_Half__c</fullName>
        <label>First Half</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public Holiday</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
                <value>
                    <fullName>Field Day</fullName>
                </value>
                <value>
                    <fullName>State sales Meeting</fullName>
                </value>
                <value>
                    <fullName>Client Training/Conference</fullName>
                </value>
                <value>
                    <fullName>Ascott Meeting</fullName>
                </value>
                <value>
                    <fullName>Annual Leave</fullName>
                </value>
                <value>
                    <fullName>Sick Leave</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Half__c</fullName>
        <label>Second Half</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public Holiday</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
                <value>
                    <fullName>Field Day</fullName>
                </value>
                <value>
                    <fullName>State sales Meeting</fullName>
                </value>
                <value>
                    <fullName>Client Training/Conference</fullName>
                </value>
                <value>
                    <fullName>Ascott Meeting</fullName>
                </value>
                <value>
                    <fullName>Annual Leave</fullName>
                </value>
                <value>
                    <fullName>Sick Leave</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Statuscheck__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Statuscheck</label>
        <type>Checkbox</type>
    </fields>
    <label>timesheet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/testTT.cls
@isTest
public class testTT{
    static testMethod void dtTests() {
    
    timesheet__c ti=new timesheet__c();
    ti.First_Half__c='yes';
    ti.Second_Half__c='No'; 
    ti.Statuscheck__c=true;
   
   ApexPages.StandardController sc = new ApexPages.StandardController(ti);
       
    test.startTest();
    
    tt t=new tt();
    t.find();
    t.addtimesheet();
    t.saveone();
    t.cancel();
    t.generatereport();
    Test.setCurrentPageReference(new PageReference('/apex/timesheet2_1')); 
    //String nextPage=t.save().getUrl();
    
    Test.setCurrentPage(Page.timesheet2);
    List<Apexpages.Message> msgs = ApexPages.getMessages();
    List<SelectOption> selOpts=t.monthList;
    
     boolean b = false;
      for(Apexpages.Message msg:msgs){
       if (msg.getDetail().contains('Work details already added to time sheet for selected date.'))
        b = true;
      }
      // system.assert(b);
    test.stopTest();
  //  System.assertEquals('/apex/timesheet2_1',nextPage); 


    }
}