retrieveUnpackaged/objects/timesheet__c.object
<CustomObject>
    <fields>
        <fullName>First_Half__c</fullName>
        <label>First Half</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public Holiday</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
                <value>
                    <fullName>Field Day</fullName>
                </value>
                <value>
                    <fullName>State sales Meeting</fullName>
                </value>
                <value>
                    <fullName>Client Training/Conference</fullName>
                </value>
                <value>
                    <fullName>Ascott Meeting</fullName>
                </value>
                <value>
                    <fullName>Annual Leave</fullName>
                </value>
                <value>
                    <fullName>Sick Leave</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Half__c</fullName>
        <label>Second Half</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public Holiday</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
                <value>
                    <fullName>Field Day</fullName>
                </value>
                <value>
                    <fullName>State sales Meeting</fullName>
                </value>
                <value>
                    <fullName>Client Training/Conference</fullName>
                </value>
                <value>
                    <fullName>Ascott Meeting</fullName>
                </value>
                <value>
                    <fullName>Annual Leave</fullName>
                </value>
                <value>
                    <fullName>Sick Leave</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>timesheet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/testTimesheet2.cls
@isTest
public class testTimesheet2{
 static testMethod void dtTests() {
      timesheet__c tis=new timesheet__c();
    tis.First_Half__c='yes';
    tis.Second_Half__c='No'; 
    ApexPages.StandardController sc = new ApexPages.StandardController(tis);
    List<Apexpages.Message> msgs = ApexPages.getMessages();
       boolean b = false;
       for(Apexpages.Message msg:msgs){
   if (msg.getDetail().contains('Work details already added to time sheet for selected date.'))
            b = true;
          }
     test.startTest();
       timesheet2 ti=new timesheet2();
       Test.setCurrentPageReference(new PageReference('/apex/timesheet2_2')); 
        List<SelectOption> selOpts=ti.monthList;
        ti.addtimesheet() ;
        ti.saveone();
        ti.find();
        ti.generatereport();
     test.stopTest();
    
 }

}